finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')) 
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('about/', views.about),
    path('birds/', views.birds_index, name='birds_index'),
    path('birds/<int:bird_id>/', views.birds_detail, name='birds_detail'),
    path('birds/create/', views.BirdCreate.as_view(), name='bird_create'),
    path('bird/<int:pk>/update/', views.BirdUpdate.as_view(), name='bird_update'),
    path('bird/<int:pk>/delete', views.BirdDelete.as_view(), name='bird_delete' ),
    path('birds/<int:bird_id>/add_feeding', views.add_feeding, name='add_feeding'),
    path('birds/<int:bird_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('birds/<int:bird_id>/remove_assoc_toy/<int:toy_id>/', views.remove_assoc_toy, name='remove_assoc_toy'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toy_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toy_create'),
    path('toy/<int:pk>/update', views.ToyUpdate.as_view(), name='toy_update'),
    path('toy/<int:pk>/delete', views.ToyDelete.as_view(), name='toy_delete'),
    path('accounts/signup', views.signup, name='signup'),
    path('birds/<int:bird_id>/add_photo', views.add_photo, name='add_photo'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Toy(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=20)

    def get_absolute_url(self):
        return reverse('toy_detail', kwargs={'pk': self.id})
    
    def __str__(self):
        return self.name

class Bird(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField(default=0)
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('birds_detail', kwargs={'bird_id': self.id})

    def __str__(self):
        return self.name

class Feeding(models.Model):
    MEALS = (
        ('B', 'Breakfast'),
        ('L', 'Lunch'),
        ('D', 'Dinner'),
    )
    date = models.DateField('feeding date')
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0][0], verbose_name='meal type')
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = '-date',
    
class Photo(models.Model):
    url = models.CharField(max_length=225)
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __STR__(self):
        return f"Photo for bird_id: {self.bird_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ('date', 'meal')

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.http import HttpResponse
from .models import Bird, Toy, Photo
from .forms import FeedingForm
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

import uuid
import boto3

S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
BUCKET = 'birdcollector-0410'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def birds_index(request):
    birds = Bird.objects.filter(user=request.user)
    return render(request, 'birds/index.html', {'birds': birds})

@login_required
def birds_detail(request, bird_id):
    bird = Bird.objects.get(id=bird_id)
    feeding_form = FeedingForm()
    bird_toy_ids = bird.toys.all().values_list('id')
    toys_bird_doesnt_have = Toy.objects.exclude(id__in=bird_toy_ids)
    return render(request, 'birds/detail.html', {'bird': bird, 'feeding_form': feeding_form, 'toys': toys_bird_doesnt_have})

@login_required
def add_feeding(request, bird_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.bird_id = bird_id
        new_feeding.save()
    return redirect('birds_detail', bird_id=bird_id)

@login_required
def assoc_toy(request, bird_id, toy_id):
    bird = Bird.objects.get(id=bird_id)
    bird.toys.add(toy_id)
    return redirect('birds_detail', bird_id=bird_id)

@login_required
def remove_assoc_toy(request, bird_id, toy_id):
    bird = Bird.objects.get(id=bird_id)
    bird.toys.remove(toy_id)
    return redirect('birds_detail', bird_id=bird_id)

def signup(request): 
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('birds_index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form, 'error': error_message})

@login_required
def add_photo(request, bird_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            Photo.objects.create(url=url, bird_id=bird_id)
        except Exception as error:
            print('photo upload failed')
            print(error)
    return redirect('birds_detail', bird_id=bird_id)


class BirdCreate(LoginRequiredMixin, CreateView):
    model = Bird
    fields = ('name', 'breed', 'description', 'age')
    template_name = 'birds/bird_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
              
        
class BirdUpdate(LoginRequiredMixin, UpdateView):
    model = Bird
    fields = ('description', 'age')
    template_name = 'birds/bird_form.html'

class BirdDelete(LoginRequiredMixin, DeleteView):
    model = Bird
    success_url = '/birds/'
    template_name = 'birds/bird_confirm_delete.html'

class ToyList(LoginRequiredMixin, ListView):
    model = Toy
    template_name = 'toys/toy_list.html'

class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy
    template_name = 'toys/toy_detail.html'

class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = '__all__'
    template_name = 'toys/toy_form.html'

class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = '__all__'
    template_name = 'toys/toy_form.html'

class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    success_url = '/toys/'
    template_name = 'toys/toy_confirm_delete.html'

main_app/templates/about.html
{% extends 'base.html' %}

{% block title%}
<title>About the Bird collector</title>
{%  endblock %}

{% block content  %}

<h1>About the Finch Collector</h1>
<p>This is a template </p>

 {% endblock %}

main_app/templates/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% block title %}
    <title>Finch Collector</title>
    {%  endblock %}
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <a class="left brand-logo" href="/">Finch Collector</a>
                <ul class="right">
                    <li>
                        <a href="/about">About</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'birds_index' %}">Birds</a>
                    </li>
                    <li>
                        <a href="{% url 'bird_create' %}">Add a Bird</a>
                    </li>
                    <li>
                        <a href="{% url 'toys_index' %}">Toys</a>
                    </li>
                    <li>
                        <a href="{% url 'toy_create' %}">Add a Toy</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
            {% block content %} 
            {%  endblock %}
    </main>
    <footer class="page-footer">
        <p>Copyright &copy; All Rights Reserved 2023 </p>
    </footer>
</body>
</html>

main_app/templates/birds/bird_confirm_delete.html
{% extends 'base.html' %}
{% block title%}
<title>Are you sure you want to delete {{ object.name }}?</title>
{% endblock %}

{% block content%}
<h1>Are you sure you want to delete {{ object.name }}?</h1>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete {{ object.name }}" class="btn red">
    <a href="{% url 'birds_detail' object.id %}" class="btn blue"> No - Cancel</a>
</form>
{% endblock %}

main_app/templates/birds/bird_form.html
{% extends 'base.html' %}

{% block title %}
{% if object %}
<title>Update {{ object.name }}</title>
{% else %}
<title>Create a Bird</title>
{% endif %}
{% endblock %}

{% block content %}
    {% if object %}
    <h1>Update {{ object.name }}</h1>
    {% else %}
    <h1>Create a Bird</h1>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"  class="btn blue">
    </form>


{% endblock %}

main_app/templates/birds/detail.html
{% extends 'base.html' %}

{% block title %}
<title>Bird Detail</title>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ bird.name }}</span>
                <p>Description: {{ bird.description }}</p>
                <p>Breed: {{ bird.breed }}</p>
                <p>Age: {{ bird.age }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'bird_update' bird.id %}">Update</a>
                <a href="{% url 'bird_delete' bird.id %}">Delete</a>
            </div>
        </div>
    {% for photo in bird.photo_set.all %}
        <img src="{{ photo.url }}" alt="{{ bird.name }}" class="responsive-img card-panel">
    {% empty %}
        <div class="card-panel blue-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' bird.id %}" method="POST" class="card-panel" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <input class="btn blue" type="submit" value="Upload Photo">
    </form>
    </div>
    <div class="col s6">
        <form action="{% url 'add_feeding' bird.id %}" method="POST">
            {%  csrf_token %}
            {{ feeding_form.as_p }}
            <input type="submit" value="Add Feeding" class="btn blue">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in bird.feeding_set.all %}
                <tr>
                    <td>{{ feeding.date }}</td>
                    <td>{{ feeding.get_meal_display }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<hr>

<div class="row">
    <div class="col s6">
        <h3>{{ bird.name }}'s Toys</h3>
        {% if bird.toys.count %}
        {% for toy in bird.toys.all %}
            <div class="card">
                <div class="card-content">
                    <span class="card-title">A <span class="{{ toy.color.lower }}-text">{{ toy.color.capitalize }}</span>{{ toy.name }}</span>
                </div>
                <div class="card-action">
                    <form action="{% url 'remove_assoc_toy' bird.id toy.id %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="remove" class="btn red">
                    </form>
                </div>
            </div>
        {% endfor %}
        {% else %}
        <h5>{{ bird.name }} doesn't have any toys yet 🐤</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Toys</h3>
        {% if toys.count %}
            {% for toy in toys %}
            <div class="card">
                <div class="card-content">
                    <span class="card-title">A <span class="{{ toy.color.lower }}-text">{{ toy.color.capitalize }}</span> {{ toy.name }}</span>
                </div>
                <div class="card-action">
                    <form action="{% url 'assoc_toy' bird.id toy.id %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="Add" class="btn blue">
                    </form>
                </div>
            </div>
            {% endfor %}
        {% else %}
        <h5>{{ bird.name }} Has All Available Toys</h5>
        {% endif %}
    </div>
</div>

<script>
    const datePickerEl = document.getElementById('id_date');
    const formPickerEl = document.getElementById('id_meal');

    M.Datepicker.init(datePickerEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true,
    });
    M.FormSelect.init(formPickerEl);
</script>

{% endblock %}

main_app/templates/birds/index.html
{% extends 'base.html' %}

{% block title %}
<title>Birds</title>
{% endblock %}

{% block content %}
<h1>Birds List</h1>
{% for bird in birds %}
<div class="card">
    <div class="card-content">
        <span class="card-title">{{ bird.name }}</span>
        <p>Description: {{ bird.description }}</p>
        <p>Breed: {{ bird.breed }}</p>
        <p>Age: {{ bird.age }}</p>
    </div>
</div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Homepage</h1>

{% endblock %}

main_app/templates/toys/toy_confirm_delete.html
{% extends 'base.html' %}
{% block title%}
<title>Are you sure you want to delete {{ object.name }}?</title>
{% endblock %}

{% block content%}
<h1>Are you sure you want to delete {{ object.name }}?</h1>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete {{ object.name }}" class="btn red">
    <a href="{% url 'toy_detail' object.id %}" class="btn blue"> No - Cancel</a>
</form>
{% endblock %}

main_app/templates/toys/toy_detail.html
{% extends 'base.html' %}

{% block title %}
<title>Toy Details</title>
{% endblock %}

{% block content %}
<div class="card">
    <span class="card-title">{{ toy.name }}</span>
    <p>{{ toy.color }}</p>
    <div class="card-action">
        <a href="{% url 'toy_update' toy.id %}">Update</a>
        <a href="{% url 'toy_delete' toy.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/toys/toy_form.html
{% extends 'base.html' %}

{% block title %}
{% if object %}
<title>Update {{ object.name }}</title>
{% else %}
<title>Create a Toy</title>
{% endif %}

{% endblock %}

{% block content %}
    {% if object %}
    <h1>Update {{ object.name }}</h1>
    {% else %}
    <h1>Create a Bird</h1>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"  class="btn blue">
    </form>


{% endblock %}

main_app/templates/toys/toy_list.html
{% extends 'base.html' %}

{% block title %}
<title>Toy List</title>
{% endblock %}

{% block content %}
<h1>Toy List</h1>

{% for toy in object_list %}
<a href="{% url 'toy_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">A <span class="{{toy.color.lower}}-text"></span> {{ toy.name }} </span>
        </div>
    </div>
</a>
{% endfor %}
{% endblock %}